package mergerequest

import (
	"fmt"
	"strings"
)

// TemplateParams contains data for generating MR/PR title and description
type TemplateParams struct {
	Prompt       string
	LinesAdded   int
	LinesRemoved int
	BranchName   string
	JobID        string
}

// GenerateTitle creates a MR/PR title from the prompt
// Format: "repobox: <truncated prompt>"
func GenerateTitle(prompt string) string {
	const maxLen = 72 // Common git title limit

	// Clean up the prompt
	prompt = strings.TrimSpace(prompt)
	prompt = strings.ReplaceAll(prompt, "\n", " ")
	prompt = strings.ReplaceAll(prompt, "\r", "")

	title := "repobox: " + prompt

	if len(title) > maxLen {
		return title[:maxLen-3] + "..."
	}

	return title
}

// GenerateDescription creates the MR/PR body with details
func GenerateDescription(params TemplateParams) string {
	var b strings.Builder

	b.WriteString("## Summary\n\n")
	b.WriteString("This pull request was automatically generated by [Repobox](https://github.com/repobox).\n\n")

	b.WriteString("### Prompt\n\n")
	b.WriteString("```\n")
	b.WriteString(params.Prompt)
	b.WriteString("\n```\n\n")

	b.WriteString("### Changes\n\n")
	b.WriteString(fmt.Sprintf("- **Lines added:** %d\n", params.LinesAdded))
	b.WriteString(fmt.Sprintf("- **Lines removed:** %d\n", params.LinesRemoved))
	b.WriteString(fmt.Sprintf("- **Net change:** %+d lines\n", params.LinesAdded-params.LinesRemoved))

	b.WriteString("\n---\n\n")
	b.WriteString(fmt.Sprintf("🤖 *Generated by Repobox* • Job ID: `%s`\n", params.JobID[:8]))

	return b.String()
}

// DetectDefaultBranch tries common default branch names
// Returns "main" as fallback
func DetectDefaultBranch(branches []string) string {
	// Priority order
	defaults := []string{"main", "master", "develop", "development"}

	for _, d := range defaults {
		for _, b := range branches {
			if b == d {
				return d
			}
		}
	}

	return "main"
}
